name: Deploy to Kubernetes and Verify

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy-and-verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google/gcloud-action@v0.3
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: qwiklabs-gcp-03-11033d5df801

    - name: Configure Docker to use GCR
      run: |
        gcloud auth configure-docker gcr.io

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/test-deployment.yaml
        kubectl apply -f kubernetes/test-service.yaml

    - name: Wait for Deployment
      run: kubectl rollout status deployment/test-deployment

    - name: Get Deployment Info
      run: kubectl get deployment test-deployment

    - name: Get Pod Info
      run: kubectl get pods

    - name: Get Service Info
      run: kubectl get service test-service

    - name: Get Events
      run: kubectl get events

    - name: View Logs
      run: |
        POD_NAME=$(kubectl get pods -o jsonpath="{.items[0].metadata.name}")
        kubectl logs $POD_NAME
